---
jobs:
- name: build-ship-it
  serial: true
  public: true
  plan:
  - aggregate:
    - get: golang-alpine-docker-image
      trigger: true
      params:
        skip_download: true
    - get: alpine-docker-golang-bash
      trigger: true
  - put: version
    params: 
      bump: minor
      annotate: version/number
  - put: alpine-bash-docker-image
    params:
      build: alpine-docker-golang-bash/
      tag: version/number
      tag_as_latest: true
  - put: alpine-docker-golang-bash 
    params: 
      only_tag: true
      repository: alpine-docker-golang-bash
      tag: version/number

      
resources:
- name: alpine-docker-golang-bash
  type: git
  source:
    uri: git@github.com:shinji62/alpine-docker-golang-bash.git
    branch: master
    private_key: {{private-key-github-concourse}}

- name: alpine-bash-docker-image
  type: gwenn-docker-image
  source:
    repository: getourneau/alpine-golang-bash
    email: {{email-docker-hub}}
    username: {{username-docker-hub}}
    password: {{password-docker-hub}}

- name: golang-alpine-docker-image
  type: docker-image
  source:
    repository: golang
    tag: 1.6-alpine

- name: version
  type: semver-gwenn
  source:
    driver: git
    uri: git@github.com:shinji62/version-concourse.git
    branch: master
    file: alpine-docker-golang-bash/version
    private_key: {{private-key-github-concourse}}
    git_user: {{concourse-user-gitinfo}}


resource_types:
- name: semver-gwenn
  type: docker-image
  source:
    repository: getourneau/semver-resource

- name: gwenn-docker-image
  type: docker-image
  source:
    repository: getourneau/docker-image-resource
